Update README.md
rasnaut/GitHubStudyPrj pull request #77
Opened 2024-06-17 10:23 UTC by vytiaganets

2024-10-17 18:23 UTC, rasnaut requested changes
Please change according to comments

2024-10-17 18:23 UTC, rasnaut commented on README.md
> +Tel~Ran@Andreas
Bad line

2024-10-17 18:25 UTC, rasnaut approved these changes

2024-10-17 18:31 UTC, merged

2024-10-19 10:19 UTC, vytiaganets commented
Удалите МЕНЯ НЕМЕДЛЕННО!!!!! с
Contributors